### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by bigbrain51** [kevinjycui/EEG-Audio-Player-Interface#1]
**I open and ran the main.py however an error occur:**
>>> 
=========== RESTART: E:\EEG-Audio-Player-Interface-master\main.py ===========
Traceback (most recent call last):
  File "E:\EEG-Audio-Player-Interface-master\main.py", line 1, in <module>
    import client
  File "E:\EEG-Audio-Player-Interface-master\client.py", line 1, in <module>
    from auth import token
  File "E:\EEG-Audio-Player-Interface-master\auth.py", line 5, in <module>
    receivedData = create_connection("wss://emotivcortex.com:54321", sslopt={"cert_reqs": ssl.CERT_NONE})
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_core.py", line 223, in connect
    options.pop('socket', None))
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_http.py", line 189, in _open_socket
    raise error
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_http.py", line 172, in _open_socket
    sock.connect(address)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
>>> 
I'm very bad at coding and don't really know what i'm even doing so, please, help me fix the problem.

**Comment by kevinjycui** [comment]
This seems to be a network error, in which your PC is not properly connecting to the websocket server. Try checking your firewall and proxy.

**Comment by bigbrain51** [comment]
**I disabled firewall and stuff and run the file again and ran into another error:**
Traceback (most recent call last):
  File "E:\EEG-Audio-Player-Interface-master\main.py", line 1, in <module>
    import client
  File "E:\EEG-Audio-Player-Interface-master\client.py", line 1, in <module>
    from auth import token
  File "E:\EEG-Audio-Player-Interface-master\auth.py", line 5, in <module>
    receivedData = create_connection("wss://emotivcortex.com:54321", sslopt={"cert_reqs": ssl.CERT_NONE})
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_core.py", line 223, in connect
    options.pop('socket', None))
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_http.py", line 197, in _open_socket
    raise err
  File "C:\Users\The Great P\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_http.py", line 172, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it 

What have i done wrong? Is there anything else i should run beside the main.py and emotiv app ?

**Comment by kevinjycui** [comment]
Sorry for the late response, but if you are still interested, this may be due to the fact that this project is now out of date. Cortex V2 was released with many changes to the documentation in the way that the device and your PC can connect to the server, and so that could be the reason for the connection not going through. You should change the url to `wss://localhost:6868`. There are other updates as well, including logging on through Emotiv's App instead of just using the websocket to log in. These changes can be found in the Cortex V2 [release notes](https://emotiv.gitbook.io/cortex-api/release-notes#changes-from-cortex-1-x-to-cortex-v-2-0). I'm sorry if it has been frustrating as I have not been active with my EEG projects, but I don't see myself updating them for Cortex V2 compatibility in the foreseeable future. Thank you.
